### ISSUE TITLE
Don't archive to project

### ISSUE THREAD

**Issue by lynch19** [spring-projects/spring-data-solr#804]
This is an awesome project and it's a great option for users. This issue is intended to show request a cancelation of moving the project to the attic.

**Comment by ipanimnim** [comment]
Agree. No reason for archiving such a great integration.

**Comment by ipanimnim** [comment]
@mp911de @christophstrobl please don't

**Comment by NicklasWallgren** [comment]
@mp911de Will we still be able to use this library once Spring Boot 3.0 is released?

**Comment by mp911de** [comment]
This project will likely not work with Spring Boot 3 because Spring Data 3.0 will introduce breaking changes. It might still work if you have only a single Spring Data module on the class path and if you force all dependencies to use Spring Data 2.x.

In any case, if there's anyone interested in maintaining this project, we're happy to help transition this project into a new groupId.

**Comment by inputinput77777** [comment]
@mp911de Why wouldn't the project keep on being held in the same Spring's ecosystem? The Spring Data project doesn't include lots of connectors, why would you prefer to get red of the existing and loved ones?

I also wonder if there's a specific feature that you're don't have priority and time to do, and whether there's an option of getting help from the community, and keep maintain it if there will be contributions.

Solr is a super important and well maintained project (check out it's repository and see that there is no day without commits). I think that keeping the project is something a lot of users want. Can you tell exactly what will be considered as a proof that this project is well wanted and needed?

**Comment by mp911de** [comment]
Spring Data for Apache Solr maintenance was discontinued by the data team as the amount of work in the general Spring Data ecosystem has increased while the team size has remained the same. At the same time, we asked for help from community maintainers but that effort didn't lead to the desired outcome to get the community involved in Spring Data Solr. In comparison to other Spring Data modules, Solr has proved to be one of the modules with lesser demand so we decided to put the module into end of life and focus on the remaining data portfolio.

All Spring code is Apache 2-licensed which means that you can fork and maintain it yourself. You are free to release Spring Data Solr using a different groupId if you want to make a fork available for everyone else.

**Comment by migroskub** [comment]
@mp911de can't you just let this repo stay inactive for some time until there will be contributions/ the team will have time to get to it? I can't see how this forced shrinking of the Spring Data ecosystem help. People using this repo, so you can probably assume that if you let it stay and add some contribution guides (like tasks) for making it work with Spring Boot 3, there will probably be some contributions. I don't see myself going to contribute to this project when it's maintained on some anonymous community's contributor, but I do see myself contributing to this project if it stays here. Please, don't archive this project.

**Comment by migroskub** [comment]
I think that the direction of this project should be that instead of moving it to the attic, just change the message in the readme to "contributions are welcome, and what's needed from contributors to make this project work with Spring 3 are the following tasks: ...". That way it will be like a "good first issue" kind of project, and developers who uses Spring Boot 2- will still be able to use this with no fear. The community wishes that this project will not get thrown to the trash. Even if there was not enough Stack Overflow questions, this doesn't mean there was no usage.

**Comment by mp911de** [comment]
We stopped shipping service releases as of November 2021. In April 2020, almost two years ago, [we announced that we want to discontinue maintenance](https://spring.io/blog/2020/04/07/spring-data-for-apache-solr-discontinued) and called for volunteers to contribute to the project. We haven't seen anyone reaching out (creating a ticket, sending an email, reaching out via Gitter) who would like to take over maintenance. And this is part of the problem. We get asked to keep up maintenance while the community doesn't commit to taking over maintenance.

Getting-started tickets can be an introduction to certain areas of a project, however, it requires a lot more than getting started for wholesome project maintenance.

We observed a couple of Spring Data community projects that went through various states of maintenance. We face a certain expectation from the community to keep project quality up to Spring standards. With the growing complexity across our Data portfolio, the core team must maintain a sharp focus and as a consequence, we cannot maintain everything. We do not want to leave projects in a state where users can no longer use those projects in production because these suffer from serious bugs or lack significant features.

As per a previous comment https://github.com/spring-projects/spring-data-solr/issues/804#issuecomment-1027736127:

> All Spring code is Apache 2-licensed which means that you can fork and maintain it yourself. > You are free to release Spring Data Solr using a different groupId if you want to make a fork available for everyone else. 

And you can ensure Spring Boot 3.0 compatibility if you want to continue using Spring Data Solr by upgrading to Spring Data Commons 3.0, Java 17 and Jakarta EE 9.

**Comment by almogtavor** [comment]
@mp911de Contributions in the near future can change your mind? I'm willing to maintain the project if it'll keep being official. Btw the announcement had 2 contributions offering. There are also some on this very thread.

Can you be more specific about the achievements and the deadlines you have for letting this project stay official?
